# v03 — Routed Few-shot

End-to-end Colab runner for `v03_routed_fewshot`. Two-pass pipeline:
1. **Pass 1**: Classify each question into (domain, answer_type) using the model
2. **Pass 2**: Solve with domain-specific system prompt + matched few-shot examples

All knobs (model, dtype, batch size, max tokens, ...) live in [`app/physics_solution/config.py`](../../config.py) — edit there, not here.

## 1. Mount Drive + chdir

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os, sys
REPO_ROOT = '/content/drive/MyDrive/NCKH/Exact_2026_Laplace-s_Red_Devils'  # change if needed
os.chdir(REPO_ROOT)
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)
print('cwd:', os.getcwd())

Mounted at /content/drive
cwd: /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils

In [2]:
!pip -q install -r app/physics_solution/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 129.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.2/668.2 kB 73.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 142.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.2/801.2 kB 82.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 9.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.1.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 5.9.0 which is incompatible.

### Install Qwen3.5 fast-attention kernels (`flash-linear-attention` + `causal-conv1d`)

On Colab Oct-2025+ runtimes both wheels install cleanly. If `causal_conv1d: False` shows up, the model still runs via torch fallback at ~3× slower — accuracy is unaffected.

In [3]:
from app.physics_solution.shared.colab.setup import install_fast_kernels
install_fast_kernels()

[install_fast_kernels] env: python=cp312 torch=2.8 cuda=12.6 -> tag cu12
[install_fast_kernels] flash-linear-attention ...
  fla: OK
[install_fast_kernels] causal-conv1d (pre-built wheels) ...
  trying v1.5.2 abi=FALSE ...
  causal-conv1d: OK (1.5.2, abi=FALSE)

{'fla': True, 'causal_conv1d': True}

In [4]:
from app.physics_solution.shared.colab.setup import setup_colab
setup_colab(repo_root=REPO_ROOT)

[colab_setup] loaded /content/drive/MyDrive/NCKH/Exact_2026_Laplace-s_Red_Devils/app/physics_solution/.env
               cwd: /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils
          hf_token: OK
         langsmith: OFF
        base_model: Qwen/Qwen3.5-4B
             dtype: bf16
            device: cuda
        batch_size: 100
    max_new_tokens: 640
       temperature: 0.0
         test_file: app/physics_solution/data/test/full_test.csv

{'cwd': '/content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils',
 'hf_token': 'OK',
 'langsmith': 'OFF',
 'base_model': 'Qwen/Qwen3.5-4B',
 'dtype': 'bf16',
 'device': 'cuda',
 'batch_size': 100,
 'max_new_tokens': 640,
 'temperature': 0.0,
 'test_file': 'app/physics_solution/data/test/full_test.csv'}

In [3]:
!nvidia-smi -L

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
GPU 0: NVIDIA A100-SXM4-40GB (UUID: GPU-0bedfb69-04c2-449f-77ee-a7fa758fc1cd)

## 2. Test set paths

Two evaluation runs: **full test** (original data) and **golden** (DeepSeek-rewritten CoT).

| File | Rows | Scope |
|---|---|---|
| `full_test.csv` | 1352 | All answer types — original CoT |
| `deepseek-v4-pro_golden_data.csv` | 1352 | All answer types — golden CoT |

In [5]:
import os

# --- Full test (original data) ---
FULL_TEST_FILE  = 'app/physics_solution/data/test/full_test.csv'
FULL_OUT_FILE   = 'app/physics_solution/versions/v03_routed_fewshot/output/results_full.json'

# --- Golden test (DeepSeek-rewritten CoT) ---
GOLDEN_TEST_FILE = 'app/physics_solution/data/golden/deepseek-v4-pro_golden_data.csv'
GOLDEN_OUT_FILE  = 'app/physics_solution/versions/v03_routed_fewshot/output/results_golden.json'

for label, f in [('Full', FULL_TEST_FILE), ('Golden', GOLDEN_TEST_FILE)]:
    assert os.path.exists(f), f"Not found: {f}"
    print(f'{label}: {f}')

Full: app/physics_solution/data/test/full_test.csv
Golden: app/physics_solution/data/golden/deepseek-v4-pro_golden_data.csv

## 3. Curate few-shot examples

Picks K examples per (domain, answer_type) group. Excludes `full_test.csv` IDs to prevent leakage.

In [6]:
!python -m app.physics_solution.versions.v03_routed_fewshot.select_fewshot --k 3 --seed 42

Excluding 0 test IDs
Candidate pool: 1352 rows across 8 domains, 6 answer types
Groups:
__prefix  __answer_type
CH        mixed              1
          pure_numeric     288
          sci_notation       1
CHLT      yes_no            20
DDT       mixed              4
          multi_value        1
          pure_numeric      78
          sci_notation      21
          text_only         25
          yes_no             1
DT        mixed              6
          pure_numeric      39
          sci_notation      23
LD        mixed              5
          pure_numeric     201
          sci_notation     190
          text_only          1
NL        mixed              8
          pure_numeric     160
          text_only         22
TD        mixed              1
          multi_value        2
          pure_numeric     166
          sci_notation       4
          text_only          4
THCB      multi_value       23
          pure_numeric      53
          text_only          4

Wrote 71 examples to /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils/app/physics_solution/versions/v03_routed_fewshot/input/examples.json
Breakdown:
__prefix  __answer_type
CH        mixed            1
          pure_numeric     3
          sci_notation     1
CHLT      yes_no           3
DDT       mixed            3
          multi_value      1
          pure_numeric     3
          sci_notation     3
          text_only        3
          yes_no           1
DT        mixed            3
          pure_numeric     3
          sci_notation     3
LD        mixed            3
          pure_numeric     3
          sci_notation     3
          text_only        1
NL        mixed            3
          pure_numeric     3
          text_only        3
TD        mixed            1
          multi_value      2
          pure_numeric     3
          sci_notation     3
          text_only        3
THCB      multi_value      3
          pure_numeric     3
          text_only        3

## 4. Inference (2-pass: classify → route → solve)

Runs both full test and golden test sequentially. All knobs (batch size, dtype, max_new_tokens, ...) come from `config.py`.

In [11]:
# --- 4a. Full test ---
!python -m app.physics_solution.cli.inference \
    --version v03_routed_fewshot \
    --test-file {FULL_TEST_FILE} \
    --out {FULL_OUT_FILE} \
    --n-examples 3 \
    --batch-size 80

[v03_routed_fewshot] loading Qwen/Qwen3.5-4B dtype=bf16 device=cuda batch_size=80
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 2 files: 100% 2/2 [00:00<00:00, 25731.93it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading weights: 100% 426/426 [00:00<00:00, 6627.35it/s]
[v03_routed_fewshot] loaded 71 few-shot examples
[v03_routed_fewshot] running on 1352 questions

--- Pass 1: classifying 1352 questions ---
Classification done in 52.9s
Domain distribution: {'DT': 218, 'LD': 248, 'CH': 290, 'NL': 159, 'CHLT': 5, 'TD': 252, 'DDT': 120, 'THCB': 60}
Answer type distribution: {'pure_numeric': 1118, 'mixed': 56, 'text_only': 113, 'sci_notation': 16, 'multi_value': 26, 'yes_no': 23}

--- Pass 2: solving 1352 questions ---
  0% 0/1352 [00:00<?, ?it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
  6% 80/1352 [01:17<20:25,  1.04it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 12% 160/1352 [02:17<16:43,  1.19it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 18% 240/1352 [03:21<15:13,  1.22it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 24% 320/1352 [04:12<12:53,  1.33it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 30% 400/1352 [04:51<10:25,  1.52it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 36% 480/1352 [06:01<10:34,  1.37it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 41% 560/1352 [07:09<10:10,  1.30it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 47% 640/1352 [08:05<08:51,  1.34it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 53% 720/1352 [09:01<07:41,  1.37it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 59% 800/1352 [09:38<05:57,  1.54it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 65% 880/1352 [10:14<04:37,  1.70it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 71% 960/1352 [10:39<03:18,  1.98it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 77% 1040/1352 [11:03<02:18,  2.26it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 83% 1120/1352 [11:40<01:44,  2.22it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 89% 1200/1352 [12:16<01:08,  2.22it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 95% 1280/1352 [12:54<00:32,  2.20it/s]  [HFBatchedLLM] generating batch of 72 prompts (max_new_tokens=640)
100% 1352/1352 [14:06<00:00,  1.60it/s]
Wrote app/physics_solution/versions/v03_routed_fewshot/output/results_full.json
Wrote app/physics_solution/versions/v03_routed_fewshot/output/results_full.csv

Accuracy: 732/1352 = 0.541
Mean latency (per question, amortised): 0.63 s
Routing accuracy (domain vs ID prefix): 926/1352 = 0.685

In [12]:
# --- 4b. Golden test ---
!python -m app.physics_solution.cli.inference \
    --version v03_routed_fewshot \
    --test-file {GOLDEN_TEST_FILE} \
    --out {GOLDEN_OUT_FILE} \
    --n-examples 3 \
    --batch-size 80

[v03_routed_fewshot] loading Qwen/Qwen3.5-4B dtype=bf16 device=cuda batch_size=80
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 2 files: 100% 2/2 [00:00<00:00, 36954.22it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading weights: 100% 426/426 [00:00<00:00, 6365.72it/s]
[v03_routed_fewshot] loaded 71 few-shot examples
[v03_routed_fewshot] running on 1352 questions

--- Pass 1: classifying 1352 questions ---
Classification done in 53.0s
Domain distribution: {'DT': 218, 'LD': 248, 'CH': 290, 'NL': 159, 'CHLT': 5, 'TD': 252, 'DDT': 120, 'THCB': 60}
Answer type distribution: {'pure_numeric': 1118, 'mixed': 56, 'text_only': 113, 'sci_notation': 16, 'multi_value': 26, 'yes_no': 23}

--- Pass 2: solving 1352 questions ---
  0% 0/1352 [00:00<?, ?it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
  6% 80/1352 [01:03<16:54,  1.25it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 12% 160/1352 [01:51<13:26,  1.48it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 18% 240/1352 [02:54<13:33,  1.37it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 24% 320/1352 [03:46<11:57,  1.44it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 30% 400/1352 [04:25<09:52,  1.61it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 36% 480/1352 [05:21<09:25,  1.54it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 41% 560/1352 [06:16<08:45,  1.51it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 47% 640/1352 [07:12<07:59,  1.49it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 53% 720/1352 [08:08<07:09,  1.47it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 59% 800/1352 [08:31<05:10,  1.78it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 65% 880/1352 [08:54<03:45,  2.09it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 71% 960/1352 [09:19<02:47,  2.34it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 77% 1040/1352 [09:43<02:01,  2.57it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 83% 1120/1352 [10:08<01:24,  2.76it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 89% 1200/1352 [10:30<00:51,  2.95it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 95% 1280/1352 [11:07<00:27,  2.65it/s]  [HFBatchedLLM] generating batch of 72 prompts (max_new_tokens=640)
100% 1352/1352 [12:07<00:00,  1.86it/s]
Wrote app/physics_solution/versions/v03_routed_fewshot/output/results_golden.json
Wrote app/physics_solution/versions/v03_routed_fewshot/output/results_golden.csv

Accuracy: 740/1352 = 0.547
Mean latency (per question, amortised): 0.54 s
Routing accuracy (domain vs ID prefix): 926/1352 = 0.685

## 5. Push to HF (with full metadata)

In [13]:
!python -m app.physics_solution.cli.upload_model \
    --version-num 3 --strategy routed_fewshot \
    --results {FULL_OUT_FILE} \
    --test-file {FULL_TEST_FILE} \
    --extra-results {GOLDEN_OUT_FILE}

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `snapshot_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 14 files:   0% 0/14 [00:00<?, ?it/s]
Downloading (incomplete total...): 100% 77.7k/77.7k [00:01<00:00, 55.1kB/s]
Fetching 14 files: 100% 14/14 [00:01<00:00,  9.27it/s]
Download complete: 100% 77.7k/77.7k [00:01<00:00, 55.1kB/s]                Snapshotted Qwen/Qwen3.5-4B -> /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils/.hf_snapshots/Qwen__Qwen3.5-4B
Download complete: 100% 77.7k/77.7k [00:02<00:00, 38.5kB/s]
Processing Files (0 / 0)      : |          |  0.00B /  0.00B
New Data Upload               : |          |  0.00B /  0.00B

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:00<?, ?B/s]

Processing Files (1 / 3)      :   0% 12.8M/9.33G [00:00<07:42, 20.2MB/s,   ???B/s  ]


  ...0002-of-00002.safetensors:   1% 31.9M/3.99G [00:00<?, ?B/s]



  ...0001-of-00002.safetensors:   0% 24.0M/5.33G [00:00<?, ?B/s]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:00<?, ?B/s]


  ...0002-of-00002.safetensors:   1% 31.9M/3.99G [00:00<?, ?B/s]



Processing Files (1 / 3)      :   1% 68.7M/9.33G [00:01<02:14, 68.6MB/s, 6.62MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:00<?, ?B/s]


  ...0002-of-00002.safetensors:   2% 84.3M/3.99G [00:00<00:18, 210MB/s]



Processing Files (1 / 3)      :   3% 241M/9.33G [00:01<00:37, 239MB/s, 23.1MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:00<?, ?B/s]


  ...0002-of-00002.safetensors:   2% 84.3M/3.99G [00:00<00:37, 105MB/s]



Processing Files (1 / 3)      :   4% 385M/9.33G [00:01<00:26, 334MB/s, 36.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:01<?, ?B/s]


  ...0002-of-00002.safetensors:   2% 84.9M/3.99G [00:00<00:55, 70.7MB/s]



Processing Files (1 / 3)      :   5% 498M/9.33G [00:01<00:24, 367MB/s, 46.1MB/s  ]
New Data Upload               :   0% 604k/134M [00:01<06:56, 321kB/s, 57.5kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:01<?, ?B/s]


  ...0002-of-00002.safetensors:   3% 106M/3.99G [00:00<00:52, 74.2MB/s]



Processing Files (1 / 3)      :   7% 663M/9.33G [00:02<00:19, 453MB/s, 60.6MB/s  ]
New Data Upload               :  16% 21.8M/134M [00:02<00:08, 13.8MB/s, 2.05MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:01<?, ?B/s]


  ...0002-of-00002.safetensors:   6% 247M/3.99G [00:01<00:21, 172MB/s]



Processing Files (1 / 3)      :  10% 932M/9.33G [00:02<00:13, 636MB/s, 84.5MB/s  ]
New Data Upload               :  40% 53.2M/134M [00:02<00:02, 34.5MB/s, 4.95MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:01<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 322M/3.99G [00:01<00:18, 193MB/s]



Processing Files (1 / 3)      :  12% 1.13G/9.33G [00:02<00:11, 688MB/s,  101MB/s  ]
New Data Upload               :  51% 68.9M/134M [00:02<00:01, 40.5MB/s, 6.30MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 324M/3.99G [00:01<00:21, 167MB/s]



Processing Files (1 / 3)      :  14% 1.29G/9.33G [00:02<00:12, 666MB/s,  113MB/s  ]
New Data Upload               :  53% 71.3M/134M [00:02<00:01, 33.4MB/s, 6.38MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 325M/3.99G [00:01<00:24, 147MB/s]



Processing Files (1 / 3)      :  15% 1.44G/9.33G [00:03<00:12, 650MB/s,  125MB/s  ]
New Data Upload               :  54% 72.5M/134M [00:03<00:02, 26.3MB/s, 6.35MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 328M/3.99G [00:02<00:27, 132MB/s]



Processing Files (1 / 3)      :  17% 1.60G/9.33G [00:03<00:12, 641MB/s,  136MB/s  ]
New Data Upload               :  56% 75.5M/134M [00:03<00:02, 22.5MB/s, 6.47MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 330M/3.99G [00:02<00:30, 119MB/s]



Processing Files (1 / 3)      :  19% 1.74G/9.33G [00:03<00:12, 624MB/s,  146MB/s  ]
New Data Upload               :  58% 77.3M/134M [00:03<00:03, 18.4MB/s, 6.49MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 332M/3.99G [00:02<00:33, 109MB/s]



Processing Files (1 / 3)      :  20% 1.88G/9.33G [00:03<00:12, 603MB/s,  156MB/s  ]
New Data Upload               :  59% 79.7M/134M [00:03<00:03, 16.0MB/s, 6.56MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:  10% 398M/3.99G [00:02<00:29, 122MB/s]



Processing Files (1 / 3)      :  22% 2.04G/9.33G [00:04<00:12, 606MB/s,  166MB/s  ]
New Data Upload               :  61% 81.6M/134M [00:04<00:03, 13.5MB/s, 6.58MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:  13% 521M/3.99G [00:03<00:23, 151MB/s]



Processing Files (1 / 3)      :  24% 2.28G/9.33G [00:04<00:09, 716MB/s,  184MB/s  ]
New Data Upload               :  63% 84.6M/134M [00:04<00:03, 13.1MB/s, 6.70MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:  16% 629M/3.99G [00:03<00:19, 170MB/s]



Processing Files (1 / 3)      :  27% 2.51G/9.33G [00:04<00:08, 774MB/s,  200MB/s  ]
New Data Upload               :  65% 87.0M/134M [00:04<00:03, 12.1MB/s, 6.77MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:  16% 631M/3.99G [00:03<00:21, 160MB/s]



Processing Files (1 / 3)      :  28% 2.65G/9.33G [00:04<00:09, 718MB/s,  209MB/s  ]
New Data Upload               :  44% 89.4M/201M [00:04<00:09, 11.4MB/s, 6.83MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:  17% 696M/3.99G [00:03<00:19, 166MB/s]



Processing Files (1 / 3)      :  30% 2.85G/9.33G [00:05<00:08, 734MB/s,  221MB/s  ]
New Data Upload               :  46% 93.1M/201M [00:05<00:08, 12.3MB/s, 7.00MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:  22% 859M/3.99G [00:04<00:16, 195MB/s]



Processing Files (1 / 3)      :  34% 3.15G/9.33G [00:05<00:07, 882MB/s,  243MB/s  ]
New Data Upload               :  60% 120M/201M [00:05<00:02, 40.4MB/s, 9.19MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 947M/3.99G [00:04<00:14, 203MB/s]



Processing Files (1 / 3)      :  36% 3.36G/9.33G [00:05<00:06, 866MB/s,  256MB/s  ]
New Data Upload               :  57% 152M/268M [00:05<00:01, 67.4MB/s, 11.9MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 960M/3.99G [00:04<00:15, 195MB/s]



Processing Files (1 / 3)      :  37% 3.49G/9.33G [00:05<00:07, 767MB/s,  262MB/s  ]
New Data Upload               :  62% 166M/268M [00:05<00:01, 63.2MB/s, 12.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 966M/3.99G [00:04<00:16, 187MB/s]



Processing Files (1 / 3)      :  39% 3.65G/9.33G [00:06<00:07, 726MB/s,  270MB/s  ]
New Data Upload               :  64% 171M/268M [00:06<00:01, 50.8MB/s, 13.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:  25% 993M/3.99G [00:05<00:16, 183MB/s]



Processing Files (1 / 3)      :  41% 3.83G/9.33G [00:06<00:07, 720MB/s,  280MB/s  ]
New Data Upload               :  74% 199M/268M [00:06<00:01, 68.1MB/s, 15.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.03G/3.99G [00:05<00:16, 181MB/s]



Processing Files (1 / 3)      :  43% 4.01G/9.33G [00:06<00:07, 721MB/s,  289MB/s  ]
New Data Upload               :  87% 233M/268M [00:06<00:00, 89.1MB/s, 17.7MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.04G/3.99G [00:05<00:16, 175MB/s]



Processing Files (1 / 3)      :  45% 4.16G/9.33G [00:06<00:07, 692MB/s,  296MB/s  ]
New Data Upload               :  91% 244M/268M [00:06<00:00, 76.3MB/s, 18.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.04G/3.99G [00:05<00:17, 168MB/s]



Processing Files (1 / 3)      :  46% 4.32G/9.33G [00:07<00:07, 670MB/s,  303MB/s  ]
New Data Upload               :  92% 247M/268M [00:07<00:00, 57.0MB/s, 18.1MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.04G/3.99G [00:06<00:18, 162MB/s]



Processing Files (1 / 3)      :  48% 4.47G/9.33G [00:07<00:07, 645MB/s,  309MB/s  ]
New Data Upload               :  93% 250M/268M [00:07<00:00, 42.8MB/s, 18.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.05G/3.99G [00:06<00:18, 156MB/s]



Processing Files (1 / 3)      :  49% 4.61G/9.33G [00:07<00:07, 629MB/s,  315MB/s  ]
New Data Upload               :  95% 254M/268M [00:07<00:00, 34.6MB/s, 17.9MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:  27% 1.09G/3.99G [00:06<00:18, 157MB/s]



Processing Files (1 / 3)      :  50% 4.71G/9.33G [00:07<00:08, 559MB/s,  317MB/s  ]
New Data Upload               :  96% 257M/268M [00:07<00:00, 28.5MB/s, 17.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:  30% 1.22G/3.99G [00:06<00:16, 169MB/s]



Processing Files (1 / 3)      :  53% 4.96G/9.33G [00:08<00:06, 684MB/s,  330MB/s  ]
New Data Upload               :  97% 261M/268M [00:08<00:00, 24.3MB/s, 17.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:  34% 1.34G/3.99G [00:07<00:14, 180MB/s]



Processing Files (1 / 3)      :  56% 5.20G/9.33G [00:08<00:05, 770MB/s,  344MB/s  ]
New Data Upload               :  98% 264M/268M [00:08<00:00, 20.7MB/s, 17.6MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.42G/3.99G [00:07<00:13, 186MB/s]



Processing Files (1 / 3)      :  58% 5.40G/9.33G [00:08<00:05, 777MB/s,  353MB/s  ]
New Data Upload               : 100% 268M/268M [00:08<00:00, 18.8MB/s, 17.6MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.42G/3.99G [00:07<00:14, 180MB/s]



Processing Files (1 / 3)      :  59% 5.54G/9.33G [00:08<00:05, 716MB/s,  358MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.43G/3.99G [00:07<00:14, 175MB/s]



Processing Files (1 / 3)      :  61% 5.69G/9.33G [00:09<00:05, 679MB/s,  363MB/s  ]
New Data Upload               :  81% 272M/335M [00:09<00:04, 14.1MB/s, 17.2MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.45G/3.99G [00:08<00:14, 171MB/s]



Processing Files (1 / 3)      :  63% 5.85G/9.33G [00:09<00:05, 670MB/s,  368MB/s  ]
New Data Upload               :  87% 290M/335M [00:09<00:01, 28.7MB/s, 18.4MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  37% 1.48G/3.99G [00:08<00:14, 170MB/s]



Processing Files (1 / 3)      :  64% 6.02G/9.33G [00:09<00:04, 671MB/s,  375MB/s  ]
New Data Upload               :  96% 322M/335M [00:09<00:00, 54.3MB/s, 20.6MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  37% 1.49G/3.99G [00:08<00:14, 167MB/s]



Processing Files (1 / 3)      :  66% 6.16G/9.33G [00:09<00:04, 639MB/s,  379MB/s  ]
New Data Upload               : 100% 335M/335M [00:09<00:00, 54.1MB/s, 21.2MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  37% 1.49G/3.99G [00:08<00:15, 162MB/s]



Processing Files (1 / 3)      :  67% 6.25G/9.33G [00:10<00:05, 553MB/s,  378MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  40% 1.58G/3.99G [00:09<00:14, 167MB/s]



Processing Files (1 / 3)      :  69% 6.42G/9.33G [00:10<00:04, 598MB/s,  385MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  42% 1.68G/3.99G [00:09<00:13, 174MB/s]



Processing Files (1 / 3)      :  71% 6.63G/9.33G [00:10<00:04, 669MB/s,  394MB/s  ]
New Data Upload               : 100% 335M/335M [00:10<00:00, 25.0MB/s, 20.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  44% 1.77G/3.99G [00:09<00:12, 178MB/s]



Processing Files (1 / 3)      :  73% 6.82G/9.33G [00:10<00:03, 698MB/s,  401MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  44% 1.77G/3.99G [00:09<00:12, 174MB/s]



Processing Files (1 / 3)      :  74% 6.95G/9.33G [00:11<00:03, 642MB/s,  403MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  44% 1.77G/3.99G [00:10<00:13, 170MB/s]



Processing Files (1 / 3)      :  76% 7.10G/9.33G [00:11<00:03, 622MB/s,  407MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:11<?, ?B/s]


  ...0002-of-00002.safetensors:  44% 1.77G/3.99G [00:10<00:13, 166MB/s]



Processing Files (2 / 3)      :  76% 7.11G/9.33G [00:11<00:04, 456MB/s,  400MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:12<?, ?B/s]


  ...0002-of-00002.safetensors:  47% 1.88G/3.99G [00:11<00:13, 158MB/s]



Processing Files (2 / 3)      :  77% 7.23G/9.33G [00:12<00:10, 206MB/s,  371MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:12<?, ?B/s]


  ...0002-of-00002.safetensors:  47% 1.89G/3.99G [00:11<00:13, 154MB/s]



Processing Files (2 / 3)      :  77% 7.23G/9.33G [00:13<00:12, 174MB/s,  364MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:13<?, ?B/s]


  ...0002-of-00002.safetensors:  48% 1.90G/3.99G [00:13<00:14, 141MB/s]



Processing Files (2 / 3)      :  78% 7.24G/9.33G [00:14<00:24, 86.9MB/s,  331MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:14<?, ?B/s]


  ...0002-of-00002.safetensors:  49% 1.96G/3.99G [00:14<00:15, 133MB/s]



Processing Files (2 / 3)      :  78% 7.31G/9.33G [00:15<00:28, 71.4MB/s,  305MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:15<?, ?B/s]


  ...0002-of-00002.safetensors:  53% 2.12G/3.99G [00:14<00:13, 141MB/s]



Processing Files (2 / 3)      :  80% 7.46G/9.33G [00:15<00:14, 131MB/s,  311MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:15<?, ?B/s]


  ...0002-of-00002.safetensors:  57% 2.28G/3.99G [00:14<00:11, 150MB/s]



Processing Files (2 / 3)      :  82% 7.62G/9.33G [00:16<00:08, 200MB/s,  317MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:15<?, ?B/s]


  ...0002-of-00002.safetensors:  59% 2.37G/3.99G [00:15<00:10, 153MB/s]



Processing Files (2 / 3)      :  83% 7.71G/9.33G [00:16<00:07, 227MB/s,  318MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:16<?, ?B/s]


  ...0002-of-00002.safetensors:  60% 2.39G/3.99G [00:16<00:11, 143MB/s]



Processing Files (2 / 3)      :  83% 7.73G/9.33G [00:17<00:13, 115MB/s,  291MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:17<?, ?B/s]


  ...0002-of-00002.safetensors:  62% 2.48G/3.99G [00:16<00:10, 146MB/s]



Processing Files (2 / 3)      :  84% 7.82G/9.33G [00:17<00:10, 148MB/s,  292MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:17<?, ?B/s]


  ...0002-of-00002.safetensors:  62% 2.49G/3.99G [00:17<00:10, 142MB/s]



Processing Files (2 / 3)      :  84% 7.83G/9.33G [00:18<00:13, 111MB/s,  282MB/s  ]
New Data Upload               :  85% 341M/402M [00:18<00:17, 3.49MB/s, 11.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:17<?, ?B/s]


  ...0002-of-00002.safetensors:  63% 2.52G/3.99G [00:17<00:10, 142MB/s]



Processing Files (2 / 3)      :  84% 7.86G/9.33G [00:18<00:13, 111MB/s,  278MB/s  ]
New Data Upload               :  92% 369M/402M [00:18<00:04, 7.67MB/s, 13.2MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:18<?, ?B/s]


  ...0002-of-00002.safetensors:  64% 2.55G/3.99G [00:17<00:10, 142MB/s]



Processing Files (2 / 3)      :  85% 7.89G/9.33G [00:18<00:12, 113MB/s,  276MB/s  ]
New Data Upload               :  99% 400M/402M [00:18<00:00, 13.9MB/s, 15.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:18<?, ?B/s]


  ...0002-of-00002.safetensors:  64% 2.55G/3.99G [00:17<00:10, 140MB/s]



Processing Files (2 / 3)      :  85% 7.89G/9.33G [00:19<00:15, 91.1MB/s,  271MB/s  ]
New Data Upload               : 100% 402M/402M [00:19<00:00, 13.6MB/s, 15.2MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:19<?, ?B/s]


  ...0002-of-00002.safetensors:  66% 2.65G/3.99G [00:18<00:09, 138MB/s]



Processing Files (2 / 3)      :  86% 7.99G/9.33G [00:20<00:14, 93.8MB/s,  258MB/s  ]
New Data Upload               : 100% 402M/402M [00:20<00:00, 9.70MB/s, 14.1MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:19<?, ?B/s]


  ...0002-of-00002.safetensors:  70% 2.80G/3.99G [00:19<00:08, 144MB/s]



Processing Files (2 / 3)      :  87% 8.14G/9.33G [00:20<00:06, 178MB/s,  265MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:19<?, ?B/s]


  ...0002-of-00002.safetensors:  74% 2.95G/3.99G [00:19<00:06, 150MB/s]



Processing Files (2 / 3)      :  89% 8.29G/9.33G [00:20<00:04, 260MB/s,  271MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:20<?, ?B/s]


  ...0002-of-00002.safetensors:  74% 2.97G/3.99G [00:19<00:06, 149MB/s]



Processing Files (2 / 3)      :  89% 8.31G/9.33G [00:20<00:04, 223MB/s,  268MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:20<?, ?B/s]


  ...0002-of-00002.safetensors:  75% 2.98G/3.99G [00:20<00:06, 146MB/s]



Processing Files (2 / 3)      :  89% 8.32G/9.33G [00:21<00:06, 145MB/s,  258MB/s  ]
New Data Upload               :  87% 410M/469M [00:21<00:06, 8.56MB/s, 13.4MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:20<?, ?B/s]


  ...0002-of-00002.safetensors:  75% 3.01G/3.99G [00:20<00:06, 145MB/s]



Processing Files (2 / 3)      :  89% 8.35G/9.33G [00:21<00:06, 140MB/s,  256MB/s  ]
New Data Upload               :  94% 441M/469M [00:21<00:01, 18.8MB/s, 15.4MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:21<?, ?B/s]


  ...0002-of-00002.safetensors:  76% 3.04G/3.99G [00:20<00:06, 145MB/s]



Processing Files (2 / 3)      :  90% 8.38G/9.33G [00:21<00:07, 134MB/s,  253MB/s  ]
New Data Upload               : 100% 469M/469M [00:21<00:00, 29.2MB/s, 17.2MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:21<?, ?B/s]


  ...0002-of-00002.safetensors:  77% 3.08G/3.99G [00:21<00:06, 142MB/s]



Processing Files (2 / 3)      :  90% 8.42G/9.33G [00:22<00:09, 93.5MB/s,  242MB/s  ]
New Data Upload               : 100% 469M/469M [00:22<00:00, 19.8MB/s, 16.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:22<?, ?B/s]


  ...0002-of-00002.safetensors:  81% 3.22G/3.99G [00:21<00:05, 147MB/s]



Processing Files (2 / 3)      :  92% 8.56G/9.33G [00:22<00:04, 186MB/s,  249MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:22<?, ?B/s]


  ...0002-of-00002.safetensors:  84% 3.36G/3.99G [00:21<00:04, 151MB/s]



Processing Files (2 / 3)      :  93% 8.70G/9.33G [00:23<00:02, 263MB/s,  254MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:22<?, ?B/s]


  ...0002-of-00002.safetensors:  88% 3.50G/3.99G [00:22<00:03, 156MB/s]



Processing Files (2 / 3)      :  95% 8.84G/9.33G [00:23<00:01, 337MB/s,  260MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:22<?, ?B/s]



## 6. Inspect results

In [14]:
import json, pandas as pd

for label, path in [('FULL', FULL_OUT_FILE), ('GOLDEN', GOLDEN_OUT_FILE)]:
    print(f'\n{"="*60}')
    print(f'  {label}: {path}')
    print(f'{"="*60}')
    data = json.loads(open(path, encoding='utf-8').read())
    print('summary:', json.dumps(data['summary'], indent=2, ensure_ascii=False))
    df = pd.DataFrame(data['rows'])
    wrong = df[~df['is_correct']].copy()
    wrong['reached_final'] = wrong['completion'].str.contains('FINAL ANSWER', case=False, regex=False)
    print(f"\nWrong: {len(wrong)} / {len(df)}")
    print(f"  ... never reached FINAL ANSWER: {(~wrong['reached_final']).sum()}")
    display(wrong[['id', 'gold_answer', 'pred_numeric', 'pred_unit', 'gold_unit', 'reached_final']].head(20))

============================================================
  FULL: app/physics_solution/versions/v03_routed_fewshot/output/results_full.json
============================================================
summary: {
  "n": 1352,
  "correct": 732,
  "accuracy": 0.5414201183431953,
  "mean_latency_s": 0.6252372414755398,
  "version": "v03_routed_fewshot",
  "model_id": "Qwen/Qwen3.5-4B",
  "dtype": "bf16",
  "effective_dtype": "bf16",
  "batch_size": 80,
  "assistant_prefix": "",
  "description": "Two-pass pipeline on the same model: Pass 1 classifies (domain, answer_type) from question text alone; Pass 2 solves with a domain-specific system prompt and answer-type-matched few-shot examples.",
  "classify_elapsed_s": 52.88875079154968,
  "n_examples": 3
}

Wrong: 620 / 1352
  ... never reached FINAL ANSWER: 13

       id       gold_answer  pred_numeric pred_unit gold_unit  reached_final
0   LD343        2.027*10^6  1.710000e+06       N/C       V/m           True
2   LD110             0.023  2.000000e+00         N         N           True
6   LD274             36.32  2.120000e+00         N         N           True
7   LD377       8.44 × 10^6  0.000000e+00       V/m       V/m           True
9   LD049             14.34  1.562500e+03         N         N           True
11  LD328         3.29*10^6  2.540000e+07       V/m       V/m           True
12  LD098      1.152 × 10^7  1.728000e+06       V/m       V/m           True
13  LD087    -2\sqrt{2} x q  2.000000e+00         C         -           True
15  LD385       3.50 × 10^6  3.840000e+06       V/m       V/m           True
16  LD083        9.6 × 10^2  2.250000e+04       V/m       V/m           True
17  LD117       0.734*10^-3  1.010000e-04         N         N           True
18  LD054             0.094  1.620000e+00         N         N           True
19  LD047  Hướng về phía q₂  2.000000e+00         -         -           True
20  LD119          12*10^-3  3.750000e-04         N         N           True
21  LD073             937.5  8.750000e+02       V/m       V/m           True
22  LD367      50.39 × 10^6  4.400000e+03       V/m       V/m           True
23  LD315        7.6 × 10^6  7.700000e+06       V/m       V/m           True
25  LD217             0.815  8.146000e+00         N         N           True
26  LD400         2.01*10^7  2.610000e+06       N/C       V/m           True
27  LD298       8.14 × 10^6  8.000000e+05       V/m       V/m           True

============================================================
  GOLDEN: app/physics_solution/versions/v03_routed_fewshot/output/results_golden.json
============================================================
summary: {
  "n": 1352,
  "correct": 740,
  "accuracy": 0.5473372781065089,
  "mean_latency_s": 0.5366514790692979,
  "version": "v03_routed_fewshot",
  "model_id": "Qwen/Qwen3.5-4B",
  "dtype": "bf16",
  "effective_dtype": "bf16",
  "batch_size": 80,
  "assistant_prefix": "",
  "description": "Two-pass pipeline on the same model: Pass 1 classifies (domain, answer_type) from question text alone; Pass 2 solves with a domain-specific system prompt and answer-type-matched few-shot examples.",
  "classify_elapsed_s": 53.0311336517334,
  "n_examples": 3
}

Wrong: 612 / 1352
  ... never reached FINAL ANSWER: 14

       id       gold_answer  pred_numeric pred_unit gold_unit  reached_final
0   LD343    2.027 * 10^{6}  1.710000e+06       N/C       V/m           True
2   LD110             0.023  2.000000e+00         N         N           True
6   LD274             36.32  2.120000e+00         N         N           True
7   LD377     8.44 * 10^{6}  0.000000e+00       V/m       V/m           True
9   LD049             14.34  1.562500e+03         N         N           True
11  LD328     3.29 * 10^{6}  2.540000e+07       V/m       V/m           True
12  LD098    1.152 * 10^{7}  1.728000e+06       V/m       V/m           True
13  LD087      -2\sqrt{2} q  2.000000e+00         C         -           True
15  LD385     3.50 * 10^{6}  3.840000e+06       V/m       V/m           True
16  LD083      9.6 * 10^{2}  2.250000e+04       V/m       V/m           True
17  LD117   0.734 * 10^{-3}  1.010000e-04         N         N           True
18  LD054             0.094  1.620000e+00         N         N           True
19  LD047  Hướng về phía q₂  2.000000e+00         -         -           True
20  LD119      12 * 10^{-3}  3.750000e-04         N         N           True
21  LD073             937.5  8.750000e+02       V/m       V/m           True
22  LD367    50.39 * 10^{6}  4.400000e+03       V/m       V/m           True
23  LD315      7.6 * 10^{6}  7.700000e+06       V/m       V/m           True
25  LD217             0.815  8.146000e+00         N         N           True
26  LD400     2.01 * 10^{7}  2.610000e+06       N/C       V/m           True
27  LD298     8.14 * 10^{6}  8.000000e+05       V/m       V/m           True

## 7. Routing accuracy check

Compare predicted domain (from Pass 1 classifier) vs the ID prefix ground truth.

In [ ]:
import re
PREFIX_RE = re.compile(r"^([A-Z]+)")

# Extract routing info from extra column
df['routed_domain'] = df['extra'].apply(lambda x: x.get('routed_domain', '') if isinstance(x, dict) else '')
df['routed_answer_type'] = df['extra'].apply(lambda x: x.get('routed_answer_type', '') if isinstance(x, dict) else '')
df['true_domain'] = df['id'].apply(lambda x: PREFIX_RE.match(str(x)).group(1) if PREFIX_RE.match(str(x)) else '')

df['domain_correct'] = df['routed_domain'] == df['true_domain']
print(f"Domain routing accuracy: {df['domain_correct'].sum()}/{len(df)} = {df['domain_correct'].mean():.3f}")

# Per-domain routing accuracy
print("\nPer-domain routing accuracy:")
for domain, sub in df.groupby('true_domain'):
    acc = sub['domain_correct'].mean()
    print(f"  {domain}: {sub['domain_correct'].sum()}/{len(sub)} = {acc:.3f}")

# Confusion: what domains were misclassified as what
misrouted = df[~df['domain_correct']]
if len(misrouted) > 0:
    print(f"\nMisrouted examples ({len(misrouted)} total):")
    print(pd.crosstab(misrouted['true_domain'], misrouted['routed_domain'], margins=True))

## 8. Deep error analysis

Open [`app/physics_solution/eda/notebooks/error_analysis.ipynb`](../../eda/notebooks/error_analysis.ipynb) — it categorises every wrong row into fail modes and writes a markdown report.