# v02 — Few-shot

End-to-end Colab runner for `v02_fewshot`. All knobs (model, dtype, batch size, max tokens, ...) live in [`app/physics_solution/config.py`](../../config.py) — edit there, not here.

Runs **directly off the Drive copy** (Colab Oct-2025+ runtime is fast enough that copying to `/content/` is no longer worth the disk churn). The repo path `REPO_ROOT` below points to your Drive folder.

## 1. Mount Drive + chdir

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os, sys
REPO_ROOT = '/content/drive/MyDrive/NCKH/Exact_2026_Laplace-s_Red_Devils'  # change if needed
os.chdir(REPO_ROOT)
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)
print('cwd:', os.getcwd())

Mounted at /content/drive
cwd: /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils

In [2]:
!pip -q install -r app/physics_solution/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 162.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.2/668.2 kB 64.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 156.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.2/801.2 kB 79.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 8.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.1.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 5.9.0 which is incompatible.

### Install Qwen3.5 fast-attention kernels (`flash-linear-attention` + `causal-conv1d`)

On Colab Oct-2025+ runtimes both wheels install cleanly. If `causal_conv1d: False` shows up, the model still runs via torch fallback at ~3× slower — accuracy is unaffected.

In [3]:
from app.physics_solution.shared.colab.setup import install_fast_kernels
install_fast_kernels()

[install_fast_kernels] env: python=cp312 torch=2.8 cuda=12.6 -> tag cu12
[install_fast_kernels] flash-linear-attention ...
  fla: OK
[install_fast_kernels] causal-conv1d (pre-built wheels) ...
  trying v1.5.2 abi=FALSE ...
  causal-conv1d: OK (1.5.2, abi=FALSE)

{'fla': True, 'causal_conv1d': True}

In [4]:
# setup_colab handles .env + LangSmith.
from app.physics_solution.shared.colab.setup import setup_colab
setup_colab(repo_root=REPO_ROOT)

[colab_setup] loaded /content/drive/MyDrive/NCKH/Exact_2026_Laplace-s_Red_Devils/app/physics_solution/.env
               cwd: /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils
          hf_token: OK
         langsmith: OFF
        base_model: Qwen/Qwen3.5-4B
             dtype: bf16
            device: cuda
        batch_size: 100
    max_new_tokens: 640
       temperature: 0.0
         test_file: app/physics_solution/data/test/full_test.csv

{'cwd': '/content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils',
 'hf_token': 'OK',
 'langsmith': 'OFF',
 'base_model': 'Qwen/Qwen3.5-4B',
 'dtype': 'bf16',
 'device': 'cuda',
 'batch_size': 100,
 'max_new_tokens': 640,
 'temperature': 0.0,
 'test_file': 'app/physics_solution/data/test/full_test.csv'}

In [5]:
!nvidia-smi -L

GPU 0: NVIDIA A100-SXM4-40GB (UUID: GPU-7f035d0e-eaf1-b7a7-9f15-f28c1f2256ba)

## 2. Test set paths

Two evaluation runs: **full test** (original data) and **golden** (DeepSeek-rewritten CoT).

| File | Rows | Scope |
|---|---|---|
| `full_test.csv` | 1352 | All answer types — original CoT |
| `deepseek-v4-pro_golden_data.csv` | 1352 | All answer types — golden CoT |

In [6]:
import os

# --- Full test (original data) ---
FULL_TEST_FILE  = 'app/physics_solution/data/test/full_test.csv'
FULL_OUT_FILE   = 'app/physics_solution/versions/v02_fewshot/output/results_full.json'

# --- Golden test (DeepSeek-rewritten CoT) ---
GOLDEN_TEST_FILE = 'app/physics_solution/data/golden/deepseek-v4-pro_golden_data.csv'
GOLDEN_OUT_FILE  = 'app/physics_solution/versions/v02_fewshot/output/results_golden.json'

for label, f in [('Full', FULL_TEST_FILE), ('Golden', GOLDEN_TEST_FILE)]:
    assert os.path.exists(f), f"Not found: {f}"
    print(f'{label}: {f}')

Full: app/physics_solution/data/test/full_test.csv
Golden: app/physics_solution/data/golden/deepseek-v4-pro_golden_data.csv

## 3. Curate few-shot examples

Picks K examples per domain prefix (drops anything in `sample_test.csv` to avoid leakage). With the full 973-sample test, the few-shot pool is tiny — re-curate with --k 1 if pool too small.

In [7]:
!python -m app.physics_solution.versions.v02_fewshot.select_fewshot --k 3 --seed 42

Excluding 50 test IDs
Candidate pool: 1302 rows (all answer types) across 8 domains
  sci_notation candidates: 365
Wrote 24 examples to /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils/app/physics_solution/versions/v02_fewshot/input/examples.json
Breakdown: {'CH': 3, 'CHLT': 3, 'DDT': 3, 'DT': 3, 'LD': 3, 'NL': 3, 'TD': 3, 'THCB': 3}

## 4. Inference

Runs both full test and golden test sequentially. All knobs (batch size, dtype, max_new_tokens, ...) come from `config.py`.

In [10]:
# --- 4a. Full test ---
!python -m app.physics_solution.cli.inference \
    --version v02_fewshot \
    --test-file {FULL_TEST_FILE} \
    --out {FULL_OUT_FILE} \
    --n-examples 3 \
    --batch-size 80

[v02_fewshot] loading Qwen/Qwen3.5-4B dtype=bf16 device=cuda batch_size=80 prefix=''
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 2 files: 100% 2/2 [00:00<00:00, 36631.48it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading weights: 100% 426/426 [00:00<00:00, 6438.66it/s]
Running on 1352 questions (batch_size=80)
  0% 0/1352 [00:00<?, ?it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
  6% 80/1352 [01:08<18:16,  1.16it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 12% 160/1352 [02:19<17:18,  1.15it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 18% 240/1352 [03:24<15:43,  1.18it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 24% 320/1352 [04:17<13:15,  1.30it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 30% 400/1352 [05:01<11:01,  1.44it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 36% 480/1352 [06:11<10:56,  1.33it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 41% 560/1352 [07:19<10:24,  1.27it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 47% 640/1352 [08:15<09:00,  1.32it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 53% 720/1352 [08:56<07:09,  1.47it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 59% 800/1352 [09:33<05:38,  1.63it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 65% 880/1352 [10:10<04:28,  1.76it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 71% 960/1352 [10:51<03:35,  1.82it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 77% 1040/1352 [11:19<02:33,  2.03it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 83% 1120/1352 [11:48<01:44,  2.22it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 89% 1200/1352 [12:10<01:00,  2.51it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 95% 1280/1352 [13:14<00:37,  1.93it/s]  [HFBatchedLLM] generating batch of 72 prompts (max_new_tokens=640)
100% 1352/1352 [14:06<00:00,  1.60it/s]
Wrote app/physics_solution/versions/v02_fewshot/output/results_full.json
Wrote app/physics_solution/versions/v02_fewshot/output/results_full.csv

Accuracy: 700/1352 = 0.518
Mean latency (per question, amortised): 0.62 s

In [11]:
# --- 4b. Golden test ---
!python -m app.physics_solution.cli.inference \
    --version v02_fewshot \
    --test-file {GOLDEN_TEST_FILE} \
    --out {GOLDEN_OUT_FILE} \
    --n-examples 3 \
    --batch-size 80

[v02_fewshot] loading Qwen/Qwen3.5-4B dtype=bf16 device=cuda batch_size=80 prefix=''
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 2 files: 100% 2/2 [00:00<00:00, 30504.03it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading weights: 100% 426/426 [00:00<00:00, 5661.71it/s]
Running on 1352 questions (batch_size=80)
  0% 0/1352 [00:00<?, ?it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
  6% 80/1352 [00:51<13:31,  1.57it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 12% 160/1352 [01:48<13:34,  1.46it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 18% 240/1352 [02:54<13:50,  1.34it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 24% 320/1352 [03:46<12:13,  1.41it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 30% 400/1352 [04:31<10:25,  1.52it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 36% 480/1352 [05:27<09:47,  1.48it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 41% 560/1352 [06:23<08:59,  1.47it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 47% 640/1352 [07:19<08:09,  1.46it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 53% 720/1352 [08:00<06:38,  1.59it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 59% 800/1352 [08:24<04:51,  1.89it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 65% 880/1352 [08:48<03:36,  2.18it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 71% 960/1352 [09:15<02:45,  2.36it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 77% 1040/1352 [09:44<02:05,  2.48it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 83% 1120/1352 [10:12<01:30,  2.57it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 89% 1200/1352 [10:34<00:53,  2.82it/s]  [HFBatchedLLM] generating batch of 80 prompts (max_new_tokens=640)
 95% 1280/1352 [11:25<00:31,  2.28it/s]  [HFBatchedLLM] generating batch of 72 prompts (max_new_tokens=640)
100% 1352/1352 [12:16<00:00,  1.84it/s]
Wrote app/physics_solution/versions/v02_fewshot/output/results_golden.json
Wrote app/physics_solution/versions/v02_fewshot/output/results_golden.csv

Accuracy: 707/1352 = 0.523
Mean latency (per question, amortised): 0.54 s

## 5. Push to HF (with full metadata)

In [12]:
!python -m app.physics_solution.cli.upload_model \
    --version-num 2 --strategy fewshot \
    --results {FULL_OUT_FILE} \
    --test-file {FULL_TEST_FILE} \
    --extra-results {GOLDEN_OUT_FILE}

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `snapshot_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 14 files:   0% 0/14 [00:00<?, ?it/s]
Fetching 14 files:   7% 1/14 [00:02<00:30,  2.32s/it]
Downloading (incomplete total...): 100% 77.7k/77.7k [00:03<00:00, 21.7kB/s]
Fetching 14 files:  21% 3/14 [00:03<00:10,  1.04it/s]
Fetching 14 files: 100% 14/14 [00:04<00:00,  3.46it/s]
Download complete: 100% 77.7k/77.7k [00:04<00:00, 21.7kB/s]                Snapshotted Qwen/Qwen3.5-4B -> /content/drive/.shortcut-targets-by-id/1QTSWNOYGynQ_AuaWq1qQpOp3mbD-KF75/NCKH/Exact_2026_Laplace-s_Red_Devils/.hf_snapshots/Qwen__Qwen3.5-4B
Download complete: 100% 77.7k/77.7k [00:04<00:00, 17.0kB/s]
Processing Files (0 / 0)      : |          |  0.00B /  0.00B
New Data Upload               : |          |  0.00B /  0.00B

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:00<?, ?B/s]

Processing Files (1 / 3)      :   0% 12.8M/9.33G [00:01<16:49, 9.23MB/s, 1.23MB/s  ]


  ...0002-of-00002.safetensors:   2% 63.9M/3.99G [00:00<?, ?B/s]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:01<?, ?B/s]


Processing Files (1 / 3)      :   1% 76.7M/9.33G [00:03<05:45, 26.8MB/s, 6.93MB/s  ]



  ...0001-of-00002.safetensors:   2% 128M/5.33G [00:00<?, ?B/s]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   2% 84.3M/3.99G [00:00<00:47, 81.7MB/s]



Processing Files (1 / 3)      :   2% 225M/9.33G [00:03<01:38, 92.5MB/s, 20.4MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   2% 84.3M/3.99G [00:00<01:35, 40.9MB/s]



Processing Files (1 / 3)      :   4% 361M/9.33G [00:03<00:57, 157MB/s, 32.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   2% 84.3M/3.99G [00:00<02:23, 27.3MB/s]



Processing Files (1 / 3)      :   5% 489M/9.33G [00:03<00:40, 217MB/s, 43.1MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   3% 107M/3.99G [00:00<01:30, 42.9MB/s]



Processing Files (1 / 3)      :   7% 640M/9.33G [00:04<00:29, 292MB/s, 55.7MB/s  ]
New Data Upload               :   0% 604k/134M [00:04<15:14, 146kB/s, 54.4kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:02<?, ?B/s]


  ...0002-of-00002.safetensors:   6% 235M/3.99G [00:01<00:27, 137MB/s]



Processing Files (1 / 3)      :  10% 896M/9.33G [00:04<00:18, 451MB/s, 77.5MB/s  ]
New Data Upload               :   1% 1.21M/134M [00:04<06:46, 327kB/s,  107kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:   6% 255M/3.99G [00:01<00:29, 127MB/s]



Processing Files (1 / 3)      :  11% 1.04G/9.33G [00:04<00:17, 476MB/s, 88.1MB/s  ]
New Data Upload               :   1% 1.81M/134M [00:04<04:05, 540kB/s,  159kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:   6% 256M/3.99G [00:01<00:34, 110MB/s]



Processing Files (1 / 3)      :  13% 1.18G/9.33G [00:04<00:16, 502MB/s, 99.1MB/s  ]
New Data Upload               :   2% 3.02M/134M [00:04<02:00, 1.09MB/s,  263kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:03<?, ?B/s]


  ...0002-of-00002.safetensors:   6% 258M/3.99G [00:01<00:38, 96.9MB/s]



Processing Files (1 / 3)      :  14% 1.33G/9.33G [00:05<00:15, 524MB/s,  110MB/s  ]
New Data Upload               :   4% 4.84M/134M [00:05<01:03, 2.03MB/s,  417kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:   7% 262M/3.99G [00:02<00:42, 88.0MB/s]



Processing Files (1 / 3)      :  16% 1.46G/9.33G [00:05<00:14, 525MB/s,  119MB/s  ]
New Data Upload               :   7% 9.07M/134M [00:05<00:26, 4.71MB/s,  779kB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:   7% 265M/3.99G [00:02<00:46, 80.6MB/s]



Processing Files (1 / 3)      :  17% 1.58G/9.33G [00:05<00:15, 516MB/s,  127MB/s  ]
New Data Upload               :   9% 12.7M/134M [00:05<00:18, 6.72MB/s, 1.08MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:   7% 269M/3.99G [00:02<00:49, 74.6MB/s]



Processing Files (1 / 3)      :  18% 1.72G/9.33G [00:05<00:14, 529MB/s,  137MB/s  ]
New Data Upload               :  12% 16.3M/134M [00:05<00:13, 8.48MB/s, 1.37MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:   7% 276M/3.99G [00:02<00:52, 70.8MB/s]



Processing Files (1 / 3)      :  20% 1.87G/9.33G [00:06<00:13, 542MB/s,  146MB/s  ]
New Data Upload               :  18% 23.6M/134M [00:06<00:08, 13.5MB/s, 1.97MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:04<?, ?B/s]


  ...0002-of-00002.safetensors:   7% 285M/3.99G [00:03<00:54, 68.2MB/s]



Processing Files (1 / 3)      :  22% 2.01G/9.33G [00:06<00:13, 553MB/s,  155MB/s  ]
New Data Upload               :  24% 32.6M/134M [00:06<00:05, 19.4MB/s, 2.71MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:   7% 293M/3.99G [00:03<00:56, 65.4MB/s]



Processing Files (1 / 3)      :  23% 2.17G/9.33G [00:06<00:12, 578MB/s,  166MB/s  ]
New Data Upload               :  30% 39.9M/134M [00:06<00:04, 22.0MB/s, 3.27MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 300M/3.99G [00:03<00:58, 62.9MB/s]



Processing Files (1 / 3)      :  25% 2.31G/9.33G [00:06<00:12, 576MB/s,  174MB/s  ]
New Data Upload               :  35% 47.2M/134M [00:06<00:03, 23.9MB/s, 3.82MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 311M/3.99G [00:03<00:59, 61.7MB/s]



Processing Files (1 / 3)      :  27% 2.48G/9.33G [00:07<00:11, 599MB/s,  185MB/s  ]
New Data Upload               :  43% 58.0M/134M [00:07<00:02, 29.5MB/s, 4.67MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:05<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 318M/3.99G [00:04<01:01, 59.8MB/s]



Processing Files (1 / 3)      :  28% 2.63G/9.33G [00:07<00:10, 610MB/s,  194MB/s  ]
New Data Upload               :  49% 65.3M/134M [00:07<00:02, 29.4MB/s, 5.18MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 325M/3.99G [00:04<01:03, 58.1MB/s]



Processing Files (1 / 3)      :  30% 2.79G/9.33G [00:07<00:10, 608MB/s,  203MB/s  ]
New Data Upload               :  54% 72.6M/134M [00:07<00:02, 29.3MB/s, 5.69MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:   8% 333M/3.99G [00:04<01:04, 56.6MB/s]



Processing Files (1 / 3)      :  31% 2.94G/9.33G [00:07<00:10, 607MB/s,  211MB/s  ]
New Data Upload               :  60% 79.8M/134M [00:07<00:01, 29.2MB/s, 6.18MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:06<?, ?B/s]


  ...0002-of-00002.safetensors:   9% 340M/3.99G [00:04<01:06, 55.2MB/s]



Processing Files (1 / 3)      :  33% 3.08G/9.33G [00:08<00:10, 597MB/s,  219MB/s  ]
New Data Upload               :  65% 87.1M/134M [00:08<00:01, 29.2MB/s, 6.66MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:   9% 351M/3.99G [00:05<01:06, 54.6MB/s]



Processing Files (1 / 3)      :  35% 3.24G/9.33G [00:08<00:09, 613MB/s,  228MB/s  ]
New Data Upload               :  73% 97.9M/134M [00:08<00:01, 33.4MB/s, 7.43MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:   9% 357M/3.99G [00:05<01:08, 53.4MB/s]



Processing Files (1 / 3)      :  36% 3.40G/9.33G [00:08<00:09, 620MB/s,  236MB/s  ]
New Data Upload               :  78% 105M/134M [00:08<00:00, 31.4MB/s, 7.82MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:   9% 365M/3.99G [00:05<01:09, 52.4MB/s]



Processing Files (1 / 3)      :  38% 3.56G/9.33G [00:08<00:09, 626MB/s,  245MB/s  ]
New Data Upload               :  84% 112M/134M [00:08<00:00, 31.4MB/s, 8.31MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:   9% 372M/3.99G [00:05<01:10, 51.4MB/s]



Processing Files (1 / 3)      :  40% 3.71G/9.33G [00:09<00:09, 619MB/s,  252MB/s  ]
New Data Upload               :  89% 120M/134M [00:09<00:00, 30.7MB/s, 8.74MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:07<?, ?B/s]


  ...0002-of-00002.safetensors:  10% 380M/3.99G [00:06<01:11, 50.5MB/s]



Processing Files (1 / 3)      :  41% 3.87G/9.33G [00:09<00:08, 625MB/s,  260MB/s  ]
New Data Upload               :  95% 127M/134M [00:09<00:00, 30.2MB/s, 9.16MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  10% 384M/3.99G [00:06<01:13, 49.2MB/s]



Processing Files (1 / 3)      :  43% 4.01G/9.33G [00:09<00:08, 606MB/s,  266MB/s  ]
New Data Upload               :  98% 131M/134M [00:09<00:00, 26.2MB/s, 9.32MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  11% 426M/3.99G [00:06<01:06, 53.6MB/s]



Processing Files (1 / 3)      :  44% 4.15G/9.33G [00:09<00:08, 589MB/s,  272MB/s  ]
New Data Upload               :  99% 133M/134M [00:09<00:00, 20.5MB/s, 9.28MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:08<?, ?B/s]


  ...0002-of-00002.safetensors:  13% 530M/3.99G [00:06<00:51, 66.6MB/s]



Processing Files (1 / 3)      :  47% 4.36G/9.33G [00:10<00:07, 662MB/s,  283MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  16% 658M/3.99G [00:07<00:40, 82.0MB/s]



Processing Files (1 / 3)      :  49% 4.62G/9.33G [00:10<00:06, 771MB/s,  298MB/s  ]
New Data Upload               : 100% 134M/134M [00:10<00:00, 11.6MB/s, 8.95MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  17% 675M/3.99G [00:07<00:40, 81.5MB/s]



Processing Files (1 / 3)      :  51% 4.77G/9.33G [00:10<00:06, 721MB/s,  305MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  17% 686M/3.99G [00:07<00:41, 80.2MB/s]



Processing Files (1 / 3)      :  53% 4.92G/9.33G [00:10<00:06, 693MB/s,  311MB/s  ]
New Data Upload               :  69% 138M/201M [00:10<00:05, 10.8MB/s, 8.98MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:09<?, ?B/s]


  ...0002-of-00002.safetensors:  20% 807M/3.99G [00:07<00:34, 93.0MB/s]



Processing Files (1 / 3)      :  55% 5.17G/9.33G [00:11<00:05, 785MB/s,  325MB/s  ]
New Data Upload               :  70% 140M/201M [00:11<00:06, 10.0MB/s, 8.94MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  23% 924M/3.99G [00:08<00:29, 104MB/s]



Processing Files (1 / 3)      :  58% 5.40G/9.33G [00:11<00:04, 823MB/s,  337MB/s  ]
New Data Upload               :  72% 144M/201M [00:11<00:04, 11.7MB/s, 9.10MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 942M/3.99G [00:08<00:29, 103MB/s]



Processing Files (1 / 3)      :  60% 5.55G/9.33G [00:11<00:04, 761MB/s,  342MB/s  ]
New Data Upload               :  55% 147M/268M [00:11<00:10, 11.8MB/s, 9.16MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 950M/3.99G [00:08<00:30, 101MB/s]



Processing Files (1 / 3)      :  61% 5.70G/9.33G [00:11<00:05, 705MB/s,  347MB/s  ]
New Data Upload               :  58% 155M/268M [00:11<00:06, 17.1MB/s, 9.61MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:10<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 953M/3.99G [00:08<00:30, 98.8MB/s]



Processing Files (1 / 3)      :  63% 5.85G/9.33G [00:12<00:05, 681MB/s,  352MB/s  ]
New Data Upload               :  59% 159M/268M [00:12<00:06, 16.4MB/s, 9.71MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:11<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 957M/3.99G [00:09<00:31, 96.6MB/s]



Processing Files (1 / 3)      :  64% 6.02G/9.33G [00:12<00:04, 673MB/s,  358MB/s  ]
New Data Upload               :  61% 163M/268M [00:12<00:06, 15.9MB/s, 9.80MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:11<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 962M/3.99G [00:09<00:32, 94.6MB/s]



Processing Files (1 / 3)      :  66% 6.17G/9.33G [00:12<00:04, 650MB/s,  363MB/s  ]
New Data Upload               :  63% 168M/268M [00:12<00:05, 17.6MB/s, 10.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:11<?, ?B/s]


  ...0002-of-00002.safetensors:  24% 970M/3.99G [00:09<00:32, 92.9MB/s]



Processing Files (2 / 3)      :  68% 6.31G/9.33G [00:12<00:04, 629MB/s,  367MB/s  ]
New Data Upload               :  65% 175M/268M [00:12<00:04, 21.0MB/s, 10.4MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:11<?, ?B/s]


  ...0002-of-00002.safetensors:  25% 979M/3.99G [00:09<00:32, 91.6MB/s]



Processing Files (2 / 3)      :  68% 6.32G/9.33G [00:13<00:06, 452MB/s,  361MB/s  ]
New Data Upload               :  69% 185M/268M [00:13<00:03, 26.2MB/s, 11.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:12<?, ?B/s]


  ...0002-of-00002.safetensors:  25% 986M/3.99G [00:10<00:33, 90.0MB/s]



Processing Files (2 / 3)      :  68% 6.33G/9.33G [00:13<00:09, 324MB/s,  354MB/s  ]
New Data Upload               :  71% 192M/268M [00:13<00:02, 26.4MB/s, 11.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:12<?, ?B/s]


  ...0002-of-00002.safetensors:  25% 995M/3.99G [00:10<00:33, 88.7MB/s]



Processing Files (2 / 3)      :  68% 6.34G/9.33G [00:13<00:12, 238MB/s,  348MB/s  ]
New Data Upload               :  75% 201M/268M [00:13<00:02, 29.4MB/s, 11.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:12<?, ?B/s]


  ...0002-of-00002.safetensors:  25% 1.00G/3.99G [00:10<00:34, 87.5MB/s]



Processing Files (2 / 3)      :  68% 6.35G/9.33G [00:13<00:16, 177MB/s,  342MB/s  ]
New Data Upload               :  78% 210M/268M [00:13<00:01, 31.5MB/s, 12.3MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:12<?, ?B/s]


  ...0002-of-00002.safetensors:  25% 1.01G/3.99G [00:10<00:34, 86.2MB/s]



Processing Files (2 / 3)      :  68% 6.35G/9.33G [00:14<00:22, 133MB/s,  336MB/s  ]
New Data Upload               :  81% 217M/268M [00:14<00:01, 30.8MB/s, 12.6MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:13<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.02G/3.99G [00:11<00:35, 84.9MB/s]



Processing Files (2 / 3)      :  68% 6.36G/9.33G [00:14<00:29, 102MB/s,  330MB/s  ]
New Data Upload               :  84% 225M/268M [00:14<00:01, 30.3MB/s, 12.9MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:13<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.03G/3.99G [00:11<00:35, 83.7MB/s]



Processing Files (2 / 3)      :  68% 6.37G/9.33G [00:14<00:37, 80.0MB/s,  324MB/s  ]
New Data Upload               :  86% 232M/268M [00:14<00:01, 29.9MB/s, 13.2MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:13<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.03G/3.99G [00:11<00:35, 82.6MB/s]



Processing Files (2 / 3)      :  68% 6.38G/9.33G [00:14<00:44, 66.2MB/s,  319MB/s  ]
New Data Upload               :  90% 240M/268M [00:14<00:00, 31.2MB/s, 13.6MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:13<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.04G/3.99G [00:11<00:36, 81.3MB/s]



Processing Files (2 / 3)      :  68% 6.38G/9.33G [00:15<00:56, 52.2MB/s,  313MB/s  ]
New Data Upload               :  91% 245M/268M [00:15<00:00, 27.6MB/s, 13.7MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:13<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.04G/3.99G [00:12<00:36, 79.9MB/s]



Processing Files (2 / 3)      :  68% 6.39G/9.33G [00:15<01:12, 40.9MB/s,  307MB/s  ]
New Data Upload               :  93% 249M/268M [00:15<00:00, 23.7MB/s, 13.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:14<?, ?B/s]


  ...0002-of-00002.safetensors:  26% 1.05G/3.99G [00:12<00:37, 78.6MB/s]



Processing Files (2 / 3)      :  68% 6.39G/9.33G [00:15<01:29, 33.0MB/s,  301MB/s  ]
New Data Upload               :  94% 252M/268M [00:15<00:00, 21.0MB/s, 13.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:14<?, ?B/s]


  ...0002-of-00002.safetensors:  28% 1.11G/3.99G [00:12<00:34, 82.4MB/s]



Processing Files (2 / 3)      :  69% 6.46G/9.33G [00:15<00:27, 105MB/s,  301MB/s  ]
New Data Upload               :  96% 256M/268M [00:15<00:00, 19.5MB/s, 13.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:14<?, ?B/s]


  ...0002-of-00002.safetensors:  32% 1.27G/3.99G [00:12<00:29, 92.8MB/s]



Processing Files (2 / 3)      :  71% 6.61G/9.33G [00:16<00:10, 260MB/s,  307MB/s  ]
New Data Upload               :  97% 260M/268M [00:16<00:00, 18.0MB/s, 13.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:14<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.42G/3.99G [00:13<00:25, 102MB/s]



Processing Files (2 / 3)      :  72% 6.76G/9.33G [00:16<00:07, 364MB/s,  313MB/s  ]
New Data Upload               :  99% 266M/268M [00:16<00:00, 19.2MB/s, 14.0MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:15<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.42G/3.99G [00:13<00:25, 101MB/s]



Processing Files (2 / 3)      :  73% 6.77G/9.33G [00:16<00:09, 257MB/s,  307MB/s  ]
New Data Upload               :  80% 268M/335M [00:16<00:04, 16.3MB/s, 13.9MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:15<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.42G/3.99G [00:13<00:26, 97.2MB/s]



Processing Files (2 / 3)      :  73% 6.77G/9.33G [00:17<00:18, 139MB/s,  295MB/s  ]
New Data Upload               :  80% 269M/335M [00:17<00:07, 9.35MB/s, 13.4MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:16<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.42G/3.99G [00:14<00:27, 93.9MB/s]



Processing Files (2 / 3)      :  73% 6.77G/9.33G [00:17<00:30, 84.0MB/s,  284MB/s  ]
New Data Upload               :  80% 269M/335M [00:17<00:11, 5.81MB/s, 12.9MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:16<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.43G/3.99G [00:14<00:27, 92.3MB/s]



Processing Files (2 / 3)      :  73% 6.77G/9.33G [00:17<00:38, 66.0MB/s,  279MB/s  ]
New Data Upload               :  80% 269M/335M [00:17<00:13, 5.06MB/s, 12.7MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:16<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.43G/3.99G [00:14<00:28, 91.1MB/s]



Processing Files (2 / 3)      :  73% 6.77G/9.33G [00:18<00:47, 54.2MB/s,  274MB/s  ]
New Data Upload               :  82% 274M/335M [00:18<00:07, 7.94MB/s, 12.8MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:17<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.43G/3.99G [00:15<00:29, 88.2MB/s]



Processing Files (2 / 3)      :  73% 6.77G/9.33G [00:18<01:16, 33.7MB/s,  264MB/s  ]
New Data Upload               :  82% 276M/335M [00:18<00:09, 6.20MB/s, 12.5MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:17<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.44G/3.99G [00:15<00:29, 87.1MB/s]



Processing Files (2 / 3)      :  73% 6.78G/9.33G [00:18<01:27, 29.4MB/s,  259MB/s  ]
New Data Upload               :  83% 279M/335M [00:18<00:06, 8.09MB/s, 12.5MB/s  ]

  ...Qwen3.5-4B/tokenizer.json: 100% 12.8M/12.8M [00:17<?, ?B/s]


  ...0002-of-00002.safetensors:  36% 1.44G/3.99G [00:15<00:29, 85.9MB/s]



Processing Files (2 / 3)      :  73% 6.78G/9.33G [00:19<01:41, 25.2MB/s,  255MB/s  ]

## 6. Inspect results

In [13]:
import json, pandas as pd

for label, path in [('FULL', FULL_OUT_FILE), ('GOLDEN', GOLDEN_OUT_FILE)]:
    print(f'\n{"="*60}')
    print(f'  {label}: {path}')
    print(f'{"="*60}')
    data = json.loads(open(path, encoding='utf-8').read())
    print('summary:', json.dumps(data['summary'], indent=2, ensure_ascii=False))
    df = pd.DataFrame(data['rows'])
    wrong = df[~df['is_correct']].copy()
    wrong['reached_final'] = wrong['completion'].str.contains('FINAL ANSWER', case=False, regex=False)
    print(f"\nWrong: {len(wrong)} / {len(df)}")
    print(f"  ... never reached FINAL ANSWER: {(~wrong['reached_final']).sum()}")
    display(wrong[['id', 'gold_answer', 'pred_numeric', 'pred_unit', 'gold_unit', 'reached_final']].head(20))

============================================================
  FULL: app/physics_solution/versions/v02_fewshot/output/results_full.json
============================================================
summary: {
  "n": 1352,
  "correct": 700,
  "accuracy": 0.5177514792899408,
  "mean_latency_s": 0.6245920342453838,
  "version": "v02_fewshot",
  "model_id": "Qwen/Qwen3.5-4B",
  "dtype": "bf16",
  "effective_dtype": "bf16",
  "batch_size": 80,
  "assistant_prefix": "",
  "description": "Few-shot prompting: K worked examples per domain are injected as prior user/assistant turns before the real question. Examples are curated by `select_fewshot.py` from the training data (test-set IDs excluded).",
  "n_examples": 3
}

Wrong: 652 / 1352
  ... never reached FINAL ANSWER: 5

       id       gold_answer  pred_numeric pred_unit gold_unit  reached_final
0   LD343        2.027*10^6  1.944000e+07       N/C       V/m           True
1   LD248             0.495  4.950000e-02         N         N           True
2   LD110             0.023  4.423000e+00         N         N           True
3   LD151        5.09*10^-4  5.091000e+00         N         N           True
6   LD274             36.32  2.117600e+00         N         N           True
7   LD377       8.44 × 10^6  1.040000e+07       V/m       V/m           True
9   LD049             14.34  1.510000e+00         N         N           True
12  LD098      1.152 × 10^7  8.640000e+05       N/C       V/m           True
13  LD087    -2\sqrt{2} x q  0.000000e+00         C         -           True
15  LD385       3.50 × 10^6  2.830000e+06       V/m       V/m           True
16  LD083        9.6 × 10^2  7.500000e+02       N/C       V/m           True
17  LD117       0.734*10^-3  9.990000e-01         N         N           True
18  LD054             0.094  0.000000e+00         N         N           True
19  LD047  Hướng về phía q₂           NaN         -         -           True
20  LD119          12*10^-3  6.000000e-02         N         N           True
21  LD073             937.5  9.375000e+00       V/m       V/m           True
22  LD367      50.39 × 10^6  6.000000e+06       V/m       V/m           True
23  LD315        7.6 × 10^6  7.100000e+07       V/m       V/m           True
24  LD018              3.12  1.800000e+00         N         N           True
25  LD217             0.815  8.146000e+01         N         N           True

============================================================
  GOLDEN: app/physics_solution/versions/v02_fewshot/output/results_golden.json
============================================================
summary: {
  "n": 1352,
  "correct": 707,
  "accuracy": 0.5229289940828402,
  "mean_latency_s": 0.5435785349656844,
  "version": "v02_fewshot",
  "model_id": "Qwen/Qwen3.5-4B",
  "dtype": "bf16",
  "effective_dtype": "bf16",
  "batch_size": 80,
  "assistant_prefix": "",
  "description": "Few-shot prompting: K worked examples per domain are injected as prior user/assistant turns before the real question. Examples are curated by `select_fewshot.py` from the training data (test-set IDs excluded).",
  "n_examples": 3
}

Wrong: 645 / 1352
  ... never reached FINAL ANSWER: 5

       id       gold_answer  pred_numeric pred_unit gold_unit  reached_final
0   LD343    2.027 * 10^{6}  1.944000e+07       N/C       V/m           True
1   LD248             0.495  4.950000e-02         N         N           True
2   LD110             0.023  4.423000e+00         N         N           True
3   LD151    5.09 * 10^{-4}  5.091000e+00         N         N           True
6   LD274             36.32  2.117600e+00         N         N           True
7   LD377     8.44 * 10^{6}  1.040000e+07       V/m       V/m           True
9   LD049             14.34  1.510000e+00         N         N           True
12  LD098    1.152 * 10^{7}  8.640000e+05       N/C       V/m           True
13  LD087      -2\sqrt{2} q  0.000000e+00         C         -           True
15  LD385     3.50 * 10^{6}  2.830000e+06       V/m       V/m           True
16  LD083      9.6 * 10^{2}  7.500000e+02       N/C       V/m           True
17  LD117   0.734 * 10^{-3}  9.990000e-01         N         N           True
18  LD054             0.094  0.000000e+00         N         N           True
19  LD047  Hướng về phía q₂           NaN         -         -           True
20  LD119      12 * 10^{-3}  6.000000e-02         N         N           True
21  LD073             937.5  9.375000e+00       V/m       V/m           True
22  LD367    50.39 * 10^{6}  6.000000e+06       V/m       V/m           True
23  LD315      7.6 * 10^{6}  7.100000e+07       V/m       V/m           True
24  LD018              3.12  1.800000e+00         N         N           True
25  LD217             0.815  8.146000e+01         N         N           True

## 7. Deep error analysis

Open [`app/physics_solution/eda/notebooks/error_analysis.ipynb`](../../eda/notebooks/error_analysis.ipynb) — it categorises every wrong row into fail modes (format / order-of-magnitude / unit / domain-specific / suspected-gold-error) and writes a markdown report.